### ISSUE TITLE
Fix some typos

### ISSUE THREAD

**Issue by alpiquero** [angelbarrera92/lab-microk8s-pod-security-policies#1]
**8.Configure-kube-system-pod-security-policy.md** and **psp/permissive.yml** have some typos.

I've noticed some other files have errors too, but I cannot remember which files have them.

**Comment by alpiquero** [comment]
Created new PR: https://github.com/intelygenz/lab-microk8s-pod-security-policies/pull/2

**Comment by angelbarrera92** [comment]
Fixed. Thanks
